server:
  port: 8081
  servlet:
    context-path: /springpoot
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JX190611?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ADMIN
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictavle-idle-timeMillis: 300000
      validation-query: select'X' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      fileters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  mvc:
    view:
      suffix: .jsp
    pathmatch:
      use-suffix-pattern: true
mybatis:
  config-location: classpath:SqlMay.xml
